Added GHA jobs to test with SSE4 and AVX-512 insns enabled, when possible.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,6 +77,22 @@ jobs:
             container: ubuntu:23.04
             install: g++-13-multilib
             address-model: 32,64
+          - toolset: gcc-13
+            cxxstd: "11,14,17,20,2b"
+            instruction-set: nehalem
+            cpu-requirements: [ sse4_1, sse4_2 ]
+            os: ubuntu-latest
+            container: ubuntu:23.04
+            install: g++-13-multilib
+            address-model: 32,64
+          - toolset: gcc-13
+            cxxstd: "11,14,17,20,2b"
+            instruction-set: skylake-avx512
+            cpu-requirements: [ avx512f, avx512cd, avx512vl, avx512dq, avx512bw, bmi1, bmi2 ]
+            os: ubuntu-latest
+            container: ubuntu:23.04
+            install: g++-13-multilib
+            address-model: 32,64
           - toolset: clang
             compiler: clang++-3.9
             cxxstd: "11,14"
@@ -158,6 +174,22 @@ jobs:
             os: ubuntu-latest
             install: clang-17
           - toolset: clang
+            compiler: clang++-17
+            cxxstd: "11,14,17,20,2b"
+            instruction-set: nehalem
+            cpu-requirements: [ sse4_1, sse4_2 ]
+            container: ubuntu:23.10
+            os: ubuntu-latest
+            install: clang-17
+          - toolset: clang
+            compiler: clang++-17
+            cxxstd: "11,14,17,20,2b"
+            instruction-set: skylake-avx512
+            cpu-requirements: [ avx512f, avx512cd, avx512vl, avx512dq, avx512bw, bmi1, bmi2 ]
+            container: ubuntu:23.10
+            os: ubuntu-latest
+            install: clang-17
+          - toolset: clang
             cxxstd: "11,14,17,2a"
             os: macos-11
           - toolset: clang
@@ -190,7 +222,7 @@ jobs:
         if: matrix.install
         run: |
           sudo apt-get update
-          sudo apt-get -y install ${{matrix.install}}
+          sudo apt-get -y install ${{join(matrix.install, ' ')}}
 
       - name: Setup Boost
         run: |
@@ -222,8 +254,23 @@ jobs:
       - name: Run tests
         run: |
           cd ../boost-root
-          export ADDRMD=${{matrix.address-model}}
-          ./b2 -j2 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} ${ADDRMD:+address-model=$ADDRMD} variant=debug,release
+          ADDRMD=${{matrix.address-model}}
+          INSTRUCTION_SET=${{matrix.instruction-set}}
+          if [ -n "${{matrix.cpu-requirements}}" ]
+          then
+            cpu_flags="$(lscpu | grep -F "Flags:" | sed "s/^Flags:\\s*//")";
+            for requirement in ${{join(matrix.cpu-requirements, ' ')}}
+            do
+              re="(^|[^[:alnum:]_])$requirement([^[:alnum:]_]|\$)"
+              if ! [[ "$cpu_flags" =~ $re ]]
+              then
+                echo "CPU lacks required feature: $requirement"
+                echo "Skipping testing"
+                exit 0
+              fi
+            done
+          fi
+          ./b2 -j2 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} ${ADDRMD:+address-model=$ADDRMD} ${INSTRUCTION_SET:+instruction-set=$INSTRUCTION_SET} variant=debug,release
 
   windows:
     strategy:
